const REQUEST_WORKFLOW_LIST = 'GET_WORKFLOWS';
const REQUEST_WORKFLOW_LIST_SUCCESS = 'GET_WORKFLOWS_SUCCESS';
const REQUEST_WORKFLOW_LIST_FAIL = 'GET_WORKFLOWS_FAIL';

const REQUEST_WORKFLOW = 'REQUEST_WORKFLOW';
const REQUEST_WORKFLOW_FAIL = 'REQUEST_WORKFLOW_FAIL';
const SELECT_WORKFLOW = 'SELECT_WORKFLOW';
const CANCEL_EDIT_WORKFLOW = 'CANCEL_EDIT_WORKFLOW';
const ADD_WORKFLOW = 'ADD_WORKFLOW';
const CANCEL_ADD_WORKFLOW = 'CANCEL_ADD_WORKFLOW';

const REQUEST_SAVE_WORKFLOW = 'REQUEST_SAVE_WORKFLOW';
const SAVE_WORKFLOW_SUCCESS = 'SAVE_WORKFLOW_SUCCESS';
const SAVE_WORKFLOW_FAIL = 'SAVE_WORKFLOW_FAIL';

const EDIT_WORKFLOW = 'EDIT_WORKFLOW';
const EDIT_WORKFLOW_TASK = 'EDIT_WORKFLOW_TASK';
const EDIT_WORKFLOW_TASK_SETTING = 'EDIT_WORKFLOW_TASK_SETTING';
const EDIT_WORKFLOW_TASK_SETTING_VARIABLE = 'EDIT_WORKFLOW_TASK_SETTING_VARIABLE'

const CHANGE_WORKFLOW_PROP = 'CHANGE_WORKFLOW_PROP';
const CHANGE_WORKFLOW_TASK_PROP = 'CHANGE_WORKFLOW_TASK_PROP';
const CHANGE_WORKFLOW_TASK_SETTING_PROP = 'CHANGE_WORKFLOW_TASK_SETTING_PROP';
const CHANGE_WORKFLOW_TASK_SETTING_VARIABLE = 'CHANGE_WORKFLOW_TASK_SETTING_VARIABLE';

const ADD_WORKFLOWW_TASK_SETTING = 'ADD_WORKFLOW_TASK_SETTING';
const ADD_WORKFLOW_TASK = 'ADD_WORKFLOW_TASK';
const ADD_WORKFLOW_TASK_SETTING_VARIABLE = 'ADD_WORKFLOW_TASK_SETTING_VARIABLE';

const DELETE_WORKFLOWW_TASK_SETTING = 'DELETE_WORKFLOW_TASK_SETTING';
const DELETE_WORKFLOW_TASK = 'DELETE_WORKFLOW_TASK';
const DELETE_WORKFLOW_TASK_SETTING_VARIABLE = 'DELETE_WORKFLOW_TASK_SETTING_VARIABLE';

export const workflowConstants = {
    REQUEST_WORKFLOW_LIST,
    REQUEST_WORKFLOW_LIST_SUCCESS,
    REQUEST_WORKFLOW_LIST_FAIL,
    REQUEST_WORKFLOW,
    REQUEST_WORKFLOW_FAIL,
    SELECT_WORKFLOW,
    EDIT_WORKFLOW,
    EDIT_WORKFLOW_TASK,
    EDIT_WORKFLOW_TASK_SETTING,
    EDIT_WORKFLOW_TASK_SETTING_VARIABLE,
    CANCEL_EDIT_WORKFLOW,
    ADD_WORKFLOW,    
    CANCEL_ADD_WORKFLOW,
    REQUEST_SAVE_WORKFLOW,
    SAVE_WORKFLOW_SUCCESS,
    SAVE_WORKFLOW_FAIL,
    CHANGE_WORKFLOW_PROP,
    CHANGE_WORKFLOW_TASK_PROP,
    ADD_WORKFLOW_TASK,
    CHANGE_WORKFLOW_TASK_SETTING_PROP,
    ADD_WORKFLOWW_TASK_SETTING,
    CHANGE_WORKFLOW_TASK_SETTING_VARIABLE,
    ADD_WORKFLOW_TASK_SETTING_VARIABLE,
    DELETE_WORKFLOW_TASK,
    DELETE_WORKFLOWW_TASK_SETTING,
    DELETE_WORKFLOW_TASK_SETTING_VARIABLE    
}