export const accountingConstants = {
  ACCOUNTING_FAILURE: "ACCOUNTING_FAILURE",

  GET_ACCOUNTING_PERIOD_LIST_REQUEST: 'ACCOUNTING_PERIOD_LIST_REQUEST',
  GET_ACCOUNTING_PERIOD_LIST_SUCCESS: 'ACCOUNTING_PERIOD_LIST_SUCCESS',

  GET_ACCOUNTING_PERIOD_REQUEST: 'ACCOUNTING_PERIOD_REQUEST',
  GET_ACCOUNTING_PERIOD_SUCCESS: 'ACCOUNTING_PERIOD_SUCCESS',

  SWITCH_TO_VIEW_MODE: "SWITCH_TO_VIEW_MODE",
  ADD_ACCOUNTING_PERIOD_INIT_REQUEST: 'ADD_ACCOUNTING_PERIOD_INIT',
  ADD_ACCOUNTING_PERIOD_INIT_SUCCESS: 'ADD_ACCOUNTING_PERIOD_INIT_SUCCESS',

  SWITCH_TO_UPDATE_MODE: "SWITCH_TO_UPDATE_MODE",
  UPDATE_ACCOUNTING_PERIOD_INIT_REQUEST: 'UPDATE_ACCOUNTING_PERIOD_INIT',
  UPDATE_ACCOUNTING_PERIOD_INIT_SUCCESS: 'UPDATE_ACCOUNTING_PERIOD_INIT_SUCCESS',

  UPDATE_ACCOUNTING_PERIOD_CHANGE: 'UPDATE_ACCOUNTING_PERIOD_CHANGE',

  SUBMIT_ACCOUNTING_PERIOD_REQUEST: 'SUBMIT_ACCOUNTING_PERIOD_REQUEST',
  SUBMIT_ACCOUNTING_PERIOD_SUCCESS: 'SUBMIT_ACCOUNTING_PERIOD_SUCCESS',



  OPEN_ACCOUNTING_PERIOD_SUCCESS: "OPEN_ACCOUNTING_PERIOD_SUCCESS",
  CLOSE_ACCOUNTING_PERIOD_SUCCESS: "CLOSE_ACCOUNTING_PERIOD_SUCCESS",
  ROLLBACK_ACCOUNT_PERIOD_SUCCESS: "ROLLBACK_ACCOUNTING_PERIOD_SUCCESS"
};
